language: php

php:
  - 7.0
  - 7.1

sudo: false

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer --version
  - composer install

script:

  - >
    echo;
    echo "Running PHP codesniffer";
    composer run php:codesniffer

  - >
    echo;
    echo "Running unit tests";
    composer php:unittests
