language: php

php:
  - 7.0
  - 7.1

env:
  matrix:
    - TYPO3_VERSION=~8.7

sudo: false

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer --version

before_script:
  - composer require typo3/cms="$TYPO3_VERSION"
  # Restore composer.json
  - git checkout composer.json
  - export TYPO3_PATH_WEB=$PWD/.Build/Web

script:

  - >
    echo;
    echo "Running PHP codesniffer";
    composer run php:codesniffer

  - >
    echo;
    echo "Running unit tests";
    composer php:unittests
