<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "importify"
 *
 * Auto generated by Extension Builder 2017-06-02
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Importify',
    'description' => 'Importer for TYPO3',
    'category' => 'be',
    'author' => 'Tim Ta',
    'author_email' => 'tim.ta@pixelant.se',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '1',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.6.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
